//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub
{


    public partial class _Default
    {

        /// <summary>pnlCategories control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCategories;

        /// <summary>rptCategories control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
    }
}
