//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub
{


    public partial class ErrorPage
    {

        /// <summary>litHeading control.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeading;

        /// <summary>litMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>lnkBack control.</summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    }
}
