//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Resources
{


    public partial class ResourceDetails
    {

        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>
        /// pnlResource control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResource;

        /// <summary>
        /// pnlDraftNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDraftNote;

        /// <summary>
        /// litCrumb control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;

        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litTypeBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTypeBadge;

        /// <summary>
        /// litCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCategory;

        /// <summary>
        /// litDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDate;

        /// <summary>
        /// litAuthor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAuthor;

        /// <summary>
        /// litDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDescription;

        /// <summary>
        /// litMedia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMedia;

        /// <summary>
        /// pnlDownload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDownload;

        /// <summary>
        /// litFileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFileName;

        /// <summary>
        /// lnkDownload control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkDownload;

        /// <summary>
        /// pnlLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLink;

        /// <summary>
        /// lnkExternal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkExternal;

        /// <summary>
        /// pnlLoginToDownload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginToDownload;

        /// <summary>
        /// pnlNothing control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNothing;
    }
}
