//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Forum
{


    public partial class CreatePost
    {

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>txtTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>ddlCategory control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>txtContent control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContent;

        /// <summary>btnPost control.</summary>
        protected global::System.Web.UI.WebControls.Button btnPost;
    }
}
