//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Forum
{


    public partial class ForumHome
    {

        /// <summary>lnkNewPost control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNewPost;

        /// <summary>pnlDeleted control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlDeleted;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>ddlCategory control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;

        /// <summary>rptPosts control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPosts;

        /// <summary>pnlEmpty control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
