//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Forum
{


    public partial class PostDetails
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>pnlPost control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPost;

        /// <summary>litCrumb control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;

        /// <summary>litTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>litCategory control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCategory;

        /// <summary>litAuthor control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAuthor;

        /// <summary>litAuthorBadge control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAuthorBadge;

        /// <summary>litDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDate;

        /// <summary>pnlHiddenNote control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlHiddenNote;

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>litContent control.</summary>
        protected global::System.Web.UI.WebControls.Literal litContent;

        /// <summary>pnlPostActions control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPostActions;

        /// <summary>btnDeletePost control.</summary>
        protected global::System.Web.UI.WebControls.Button btnDeletePost;

        /// <summary>litReplyCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litReplyCount;

        /// <summary>rptReplies control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptReplies;

        /// <summary>pnlNoReplies control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoReplies;

        /// <summary>pnlReplyForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlReplyForm;

        /// <summary>txtReply control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtReply;

        /// <summary>btnReply control.</summary>
        protected global::System.Web.UI.WebControls.Button btnReply;

        /// <summary>pnlLoginToReply control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginToReply;
    }
}
