//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class AssignmentDetails
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>pnlAssignment control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAssignment;

        /// <summary>litCrumb control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;

        /// <summary>litTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>litStatusBadge control.</summary>
        protected global::System.Web.UI.WebControls.Literal litStatusBadge;

        /// <summary>litDue control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDue;

        /// <summary>litMaxMarks control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMaxMarks;

        /// <summary>litDescription control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDescription;

        /// <summary>pnlInstructions control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlInstructions;

        /// <summary>litInstructions control.</summary>
        protected global::System.Web.UI.WebControls.Literal litInstructions;

        /// <summary>pnlAttachment control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAttachment;

        /// <summary>lnkInstructions control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkInstructions;

        /// <summary>pnlNoSubmission control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSubmission;

        /// <summary>pnlSubmission control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSubmission;

        /// <summary>litSubmittedDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSubmittedDate;

        /// <summary>pnlComment control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlComment;

        /// <summary>litComment control.</summary>
        protected global::System.Web.UI.WebControls.Literal litComment;

        /// <summary>pnlReturned control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlReturned;

        /// <summary>litReturnedNote control.</summary>
        protected global::System.Web.UI.WebControls.Literal litReturnedNote;

        /// <summary>pnlGrade control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlGrade;

        /// <summary>litMarks control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMarks;

        /// <summary>litFeedback control.</summary>
        protected global::System.Web.UI.WebControls.Literal litFeedback;

        /// <summary>lnkMySubmission control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkMySubmission;

        /// <summary>pnlCanSubmit control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCanSubmit;

        /// <summary>lnkSubmit control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkSubmit;

        /// <summary>pnlLocked control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlLocked;

        /// <summary>litLockedReason control.</summary>
        protected global::System.Web.UI.WebControls.Literal litLockedReason;
    }
}
