//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class Dashboard
    {

        /// <summary>
        /// lblFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullName;

        /// <summary>
        /// lblResources control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResources;

        /// <summary>
        /// lblPending control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPending;

        /// <summary>
        /// lblSubmitted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubmitted;

        /// <summary>
        /// lblAttempts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAttempts;

        /// <summary>
        /// rptAnnouncements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAnnouncements;

        /// <summary>
        /// pnlNoAnnouncements control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAnnouncements;

        /// <summary>
        /// rptAssignments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAssignments;

        /// <summary>
        /// pnlNoAssignments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoAssignments;

        /// <summary>
        /// rptForumPosts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptForumPosts;

        /// <summary>
        /// pnlNoPosts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoPosts;
    }
}
