//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class Profile
    {

        /// <summary>
        /// lblProfileMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProfileMessage;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// lblMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMemberSince;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// lblPasswordMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPasswordMessage;

        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
