//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class QuizResult
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>pnlResult control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>litQuizTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;

        /// <summary>litDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDate;

        /// <summary>divRing control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRing;

        /// <summary>litPercentRing control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPercentRing;

        /// <summary>litScore control.</summary>
        protected global::System.Web.UI.WebControls.Literal litScore;

        /// <summary>litTotal control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>litPercentage control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPercentage;

        /// <summary>phCounts control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCounts;

        /// <summary>litCorrect control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCorrect;

        /// <summary>litWrong control.</summary>
        protected global::System.Web.UI.WebControls.Literal litWrong;

        /// <summary>litBlank control.</summary>
        protected global::System.Web.UI.WebControls.Literal litBlank;

        /// <summary>phReviewButton control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phReviewButton;

        /// <summary>lnkReview control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkReview;

        /// <summary>lnkRetake control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRetake;

        /// <summary>pnlReview control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlReview;

        /// <summary>rptReview control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptReview;
    }
}
