//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class Quizzes
    {

        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;

        /// <summary>rptQuizzes control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;

        /// <summary>pnlEmpty control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
