//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class SubmitAssignment
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>pnlAssignment control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlAssignment;

        /// <summary>lnkBack control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBack;

        /// <summary>litCrumb control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;

        /// <summary>litTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>litDue control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDue;

        /// <summary>litMaxMarks control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMaxMarks;

        /// <summary>pnlClosed control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlClosed;

        /// <summary>litClosedReason control.</summary>
        protected global::System.Web.UI.WebControls.Literal litClosedReason;

        /// <summary>lnkBackClosed control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBackClosed;

        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>pnlExisting control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlExisting;

        /// <summary>litExistingDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litExistingDate;

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>fuAssignment control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuAssignment;

        /// <summary>cvFile control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvFile;

        /// <summary>txtComment control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtComment;

        /// <summary>btnSubmit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>lnkCancel control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkCancel;
    }
}
