//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Student
{


    public partial class TakeQuiz
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>pnlQuiz control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>litCrumb control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;

        /// <summary>litTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>litQuestionCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litQuestionCount;

        /// <summary>litTotalMarks control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalMarks;

        /// <summary>litTimeLimit control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTimeLimit;

        /// <summary>pnlExpired control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlExpired;

        /// <summary>litExpired control.</summary>
        protected global::System.Web.UI.WebControls.Literal litExpired;

        /// <summary>lnkRestart control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRestart;

        /// <summary>pnlTake control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlTake;

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>spanTimer control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanTimer;

        /// <summary>litTotalQuestions control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTotalQuestions;

        /// <summary>rptQuestions control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>btnSubmit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
