//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class Dashboard
    {

        /// <summary>lblFullName control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFullName;

        /// <summary>lblStudents control.</summary>
        protected global::System.Web.UI.WebControls.Label lblStudents;
        /// <summary>lblStudentsSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblStudentsSub;

        /// <summary>lblResources control.</summary>
        protected global::System.Web.UI.WebControls.Label lblResources;
        /// <summary>lblResourcesSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblResourcesSub;

        /// <summary>lblAssignments control.</summary>
        protected global::System.Web.UI.WebControls.Label lblAssignments;
        /// <summary>lblAssignmentsSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblAssignmentsSub;

        /// <summary>lblSubmissions control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSubmissions;
        /// <summary>lblSubmissionsSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSubmissionsSub;

        /// <summary>lblQuizzes control.</summary>
        protected global::System.Web.UI.WebControls.Label lblQuizzes;
        /// <summary>lblQuizzesSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblQuizzesSub;

        /// <summary>lblAnnouncements control.</summary>
        protected global::System.Web.UI.WebControls.Label lblAnnouncements;
        /// <summary>lblAnnouncementsSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblAnnouncementsSub;

        /// <summary>lblForumPosts control.</summary>
        protected global::System.Web.UI.WebControls.Label lblForumPosts;
        /// <summary>lblForumPostsSub control.</summary>
        protected global::System.Web.UI.WebControls.Label lblForumPostsSub;

        /// <summary>rptRegistrations control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptRegistrations;
        /// <summary>pnlNoRegistrations control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoRegistrations;

        /// <summary>rptSubmissions control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptSubmissions;
        /// <summary>pnlNoSubmissions control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSubmissions;

        /// <summary>rptForum control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptForum;
        /// <summary>pnlNoForum control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoForum;
    }
}
