//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageQuizzes
    {

        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;
        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        /// <summary>txtTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        /// <summary>txtDescription control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        /// <summary>txtTimeLimit control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTimeLimit;
        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        /// <summary>cvStatus control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvStatus;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>gvQuizzes control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvQuizzes;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
