//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageAssignments
    {

        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;
        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        /// <summary>txtTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        /// <summary>txtDescription control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        /// <summary>txtInstructions control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtInstructions;
        /// <summary>txtDueDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        /// <summary>cvDueDate control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvDueDate;
        /// <summary>txtMaxMarks control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMaxMarks;
        /// <summary>cvMaxMarks control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvMaxMarks;
        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        /// <summary>fuInstructions control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuInstructions;
        /// <summary>lblCurrentFile control.</summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentFile;
        /// <summary>chkRemoveFile control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRemoveFile;
        /// <summary>cvFile control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvFile;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        /// <summary>ddlDueFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDueFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>gvAssignments control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvAssignments;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
