//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageResources
    {

        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;
        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        /// <summary>txtTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        /// <summary>ddlCategory control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        /// <summary>txtDescription control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        /// <summary>ddlResourceType control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlResourceType;
        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        /// <summary>fuDocument control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuDocument;
        /// <summary>lblCurrentDocument control.</summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentDocument;
        /// <summary>cvDocument control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvDocument;
        /// <summary>fuVideo control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuVideo;
        /// <summary>lblCurrentVideo control.</summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentVideo;
        /// <summary>cvVideo control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvVideo;
        /// <summary>fuAudio control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuAudio;
        /// <summary>lblCurrentAudio control.</summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentAudio;
        /// <summary>cvAudio control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvAudio;
        /// <summary>txtExternalUrl control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtExternalUrl;
        /// <summary>cvUrl control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvUrl;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlCategoryFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        /// <summary>ddlTypeFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTypeFilter;
        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>gvResources control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvResources;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
