//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageAnnouncements
    {

        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;
        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        /// <summary>txtTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        /// <summary>txtContent control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContent;
        /// <summary>txtPublishDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPublishDate;
        /// <summary>cvPublish control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvPublish;
        /// <summary>txtExpiryDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtExpiryDate;
        /// <summary>cvExpiry control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvExpiry;
        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlStateFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStateFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>gvAnnouncements control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvAnnouncements;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
