//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageUsers
    {

        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;

        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;

        /// <summary>txtFullName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>txtUsername control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>lblUsernameHelp control.</summary>
        protected global::System.Web.UI.WebControls.Label lblUsernameHelp;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>txtPassword control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>lblPasswordHelp control.</summary>
        protected global::System.Web.UI.WebControls.Label lblPasswordHelp;

        /// <summary>ddlRole control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>lblSelfNote control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSelfNote;

        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>ddlRoleFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRoleFilter;

        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;

        /// <summary>gvUsers control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;

        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
