//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageQuestions
    {

        /// <summary>pnlNotFound control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        /// <summary>pnlQuiz control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        /// <summary>litCrumb control.</summary>
        protected global::System.Web.UI.WebControls.Literal litCrumb;
        /// <summary>litTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;
        /// <summary>litStatusBadge control.</summary>
        protected global::System.Web.UI.WebControls.Literal litStatusBadge;
        /// <summary>litSummary control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;
        /// <summary>btnAdd control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;
        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>lblFormTitle control.</summary>
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        /// <summary>lblAttemptsWarning control.</summary>
        protected global::System.Web.UI.WebControls.Label lblAttemptsWarning;
        /// <summary>txtQuestion control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuestion;
        /// <summary>txtOptionA control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtOptionA;
        /// <summary>txtOptionB control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtOptionB;
        /// <summary>txtOptionC control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtOptionC;
        /// <summary>txtOptionD control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtOptionD;
        /// <summary>cvDistinct control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvDistinct;
        /// <summary>rblCorrect control.</summary>
        protected global::System.Web.UI.WebControls.RadioButtonList rblCorrect;
        /// <summary>txtMarks control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarks;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>gvQuestions control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvQuestions;
    }
}
