//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageForum
    {

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>lnkPostsTab control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkPostsTab;
        /// <summary>lnkRepliesTab control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRepliesTab;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        /// <summary>pnlCategoryFilter control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlCategoryFilter;
        /// <summary>ddlCategoryFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoryFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lnkReset control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkReset;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>pnlPosts control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlPosts;
        /// <summary>gvPosts control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvPosts;
        /// <summary>pnlReplies control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlReplies;
        /// <summary>gvReplies control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvReplies;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
