//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSkillHub.Admin
{


    public partial class ManageSubmissions
    {

        /// <summary>lblMessage control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
        /// <summary>pnlForm control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        /// <summary>litStudent control.</summary>
        protected global::System.Web.UI.WebControls.Literal litStudent;
        /// <summary>litAssignment control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAssignment;
        /// <summary>litSubmitted control.</summary>
        protected global::System.Web.UI.WebControls.Literal litSubmitted;
        /// <summary>lnkFile control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkFile;
        /// <summary>pnlStudentComment control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlStudentComment;
        /// <summary>litStudentComment control.</summary>
        protected global::System.Web.UI.WebControls.Literal litStudentComment;
        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        /// <summary>txtMarks control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMarks;
        /// <summary>lblMaxHint control.</summary>
        protected global::System.Web.UI.WebControls.Label lblMaxHint;
        /// <summary>cvMarks control.</summary>
        protected global::System.Web.UI.WebControls.CustomValidator cvMarks;
        /// <summary>txtFeedback control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFeedback;
        /// <summary>btnSave control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
        /// <summary>btnCancel control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        /// <summary>ddlAssignment control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignment;
        /// <summary>ddlStatusFilter control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        /// <summary>btnSearch control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        /// <summary>lblSummary control.</summary>
        protected global::System.Web.UI.WebControls.Label lblSummary;
        /// <summary>gvSubmissions control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvSubmissions;
        /// <summary>litPager control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPager;
    }
}
